swagger: '2.0'
info:
  version: '1.0.0'
  title: CARMIN a Common web API for Remote pipeline INvocation
  description: FLI/IAM REST API for exchanging data and remote calling pipelines.
    
  #termsOfService: http://helloreverb.com/terms/
  #contact:
    #name: Swagger API team
    #email: foo@example.com
    #url: http://swagger.io
  #license:
    #name: MIT
    #url: http://opensource.org/licenses/MIT
#host: petstore.swagger.io
#basePath: /api
security: 
  - {basicAuth:[]}
  - {apiKey:[]}
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json

securityDefinitions:
  basicAuth:
    type: basic
    description: If supported by the platfrom, it is possible to use HTTP
      Basic Authentication but one must call `/login_basic_http` before 
      calling any API service.
  apiKey:
      # TODO: Should we replace cookie authentication (not supported by Swagger)
      # by apiKey authentication ?
      type: apiKey
      name: api_key
      in: header
      description: If HTTP Basic authentication is not supported, calling
        `/login` allows for password checking and coockie based authentication.

paths:
  /login:
    get:
      description: |
        Check username and password and allow access to the API in case of 
        success by setting a cookie that must be used in any subsequent API
        calls.
      operationId: authenticateSession
      parameters:
        - name: username
          in: query
          description: Name of the user account.
          required: true
          type: string
          format: utf8
        - name: password
          in: query
          description: Password to verify.
          required: true
          type: string
          format: password
      responses:
        '200':
          description: Returns `success` if login is succesful or `failure`
            if login and/or password is incorrect.
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorCodeAndMessage'
      
  /platform:
    get:
      description: Returns information about the platform
      operationId: getPlatformProperties
      produces:
        - application/json
      responses:
        '200':
          description: succesful response
          schema:
            $ref: '#/definitions/platformProperties'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorCodeAndMessage'

  /pipelines:
    get:
      description: Returns a list of available pipelines
      operationId: listPipelines
      produces:
        - application/json
      responses:
        '200':
          description: succesful response
          schema:
            type: array
            items:
              $ref: '#/definitions/Pipeline'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorCodeAndMessage'
            
definitions:
  platformProperties:
    type: object
    required:
      - platformName
      - supportedTransferProtocols
      - supportedModules
      - defaultLimitListExecutions
      - unsupportedMethods
      - supportedAPIVersion
    properties:
      platformName:
        type: string
        description: Name of the platform.
      APIErrorCodesAndMessages:
        type: array
        items:
          $ref: '#/definitions/errorCodeAndMessage'
      supportedTransferProtocols:
        type: array
        items:
          type: string
        description: Used in getExecutionResults and getAccessURL. Protocol names must be URL prefixes (e.g. “http”, “https”, “ftp”, “sftp”, “ftps”, “scp”, “webdav”). 
      supportedModules:
        type: array
        items:
          type: string # TODO: How to define an enum in Swagger ?
      defaultLimitListExecutions:
        type: integer
        format: int64
        description: The number of Executions returned by Execution.listExecution when limit is not specified.
      email:
        type: string
        format: utf8 # TODO: I do not know if utf8 is valid here.
      platformDescription:
        type: string
        format: utf8
      minAuthorizedExecutionTimeout:
        type: integer
        format: int64
      maxAuthorizedExecutionTimeout:
        type: integer
        format: int64
        description: 0 or absent means no max timeout. max has to be greater or equal to the min.
      defaultExecutionTimeout:
        type: integer
        format: int64
      unsupportedMethods:
        type: array
        items:
          type: string
        description: List of optional methods that are not supported by the platform.
      maxSizeDirectTransfer:
        type: integer
        format: int64
        description: The maximal size of files and directories that can be transferred by methods Path.uploadPath and Path.downloadPath.
      defaultStudy:
        type: string
      supportedAPIVersion:
        type: string
  
  
  
  PipelineParameter:
    type: object
    required:
      - name
      - paramType
      - isOptional
      - isReturnedValue
    properties:
      name:
        type: string
      paramType:
        type: string
      isOptional:
        type: boolean
      isReturnedValue:
        type: boolean
      defaultValue:
        type: string
      description:
        type: string
        format: utf8
      
  
  
  
  
  Pipeline:
    type: object
    required:
      - identifier
      - name
      - version
    properties:
      identifier:
        type: string
      name:
        type: string
        format: utf8
      version:
        type: string
      description:
        type: string
        format: utf8
      canExecute:
        type: boolean
  errorCodeAndMessage:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
    